"""empty message

Revision ID: 2da0981e2733
Revises: ba0289a51b92
Create Date: 2017-12-09 17:39:50.389369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2da0981e2733'
down_revision = 'ba0289a51b92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('request', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('foreign_contact', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['foreign_contact'], ['foreign_contacts.id'], ),
    sa.ForeignKeyConstraint(['request'], ['requests.id'], ),
    sa.ForeignKeyConstraint(['user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('contact_log')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_log',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('request', sa.INTEGER(), nullable=False),
    sa.Column('user', sa.INTEGER(), nullable=True),
    sa.Column('foreign_contact', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['foreign_contact'], ['foreign_contacts.id'], ),
    sa.ForeignKeyConstraint(['request'], ['requests.id'], ),
    sa.ForeignKeyConstraint(['user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('contact_logs')
    # ### end Alembic commands ###
