"""add location to foreign contacts and set email as not nullable

Revision ID: 7ae3c2b07078
Revises: 2da0981e2733
Create Date: 2017-12-09 18:10:10.446915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ae3c2b07078'
down_revision = '2da0981e2733'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('foreign_contacts', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('foreign_contacts', sa.Column('lng', sa.Float(), nullable=True))
    op.add_column('foreign_contacts', sa.Column('location', sa.String(), nullable=True))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('foreign_contacts', 'location')
    op.drop_column('foreign_contacts', 'lng')
    op.drop_column('foreign_contacts', 'lat')
    # ### end Alembic commands ###
